### ISSUE TITLE
Fix region name for Ile de la Madeleine

### ISSUE THREAD

**Issue by grassick** [Ouranosinc/scenario-web#2]
This appears to be an issue with the shape files, as this is where I get the names from

**Comment by tlogan2000** [comment]
I've put a Regions.zip in my google drive with the corrected .shp:
https://drive.google.com/open?id=1B2t-IxYOkGP_goAil78mZe6w--XqWb_J

**Comment by grassick** [comment]
Thanks!

**Comment by grassick** [comment]
Would you be able to update the temporal data as it will need the name fixed there as well? I can hack the file I have for now, so not urgent.

**Comment by tlogan2000** [comment]
Yes I can re-run the script... it reads in the shapefile as well. Might take a little while to run. 
Can you just hack it for now? thx

**Comment by grassick** [comment]
No problem at all. I'm going to assign a few more issues to you just to keep track of what needs to get done.

**Comment by grassick** [comment]
@tlogan2000 Can you save the file in UTF-8 encoding? The importer expects that encoding rather than ISO-8852. I can convert if that ends up being a problem

**Comment by tlogan2000** [comment]
I put a new version of the 'Regions_CSV_data.zip' and 'SpatialMapping_CSV_data.zip' on my drive:
They should be in UTF-8 now .. is there an easy way to check the encoding of the files?   Couldn't find a two second answer .. anyways I think it should be ok

https://drive.google.com/open?id=1B2t-IxYOkGP_goAil78mZe6w--XqWb_J

**Comment by grassick** [comment]
The file is utf-8 now, thank you! There is a discrepancy in one name, however:
`Gaspésie - Îles-de-la-Madeleine`
vs
`Gaspésie - Îles de la Madeleine`

which one is correct? I can hack it either way for now.

**Comment by tlogan2000** [comment]
Gaspésie - Îles-de-la-Madeleine  : seems to be the more official version. sorry for that

**Comment by tlogan2000** [comment]
re uploaded the corrected .shp to the google drive folder as well (Regions.zip)
